name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Run Tests
      run: mvn verify

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          target/failsafe-reports/TEST-*.xml
          target/surefire-reports/TEST-*.xml
      if: always()
